In [1]:
# Q1: Data type of list_ and array_list

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

# Printing data types of both variables
print(f"Data type of list_: {type(list_)}")
print(f"Data type of array_list: {type(array_list)}")


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [2]:
## Q2: Data type of each element in list_ and array_list

# Printing data types of each element in list_
print("Data types in list_:")
for element in list_:
    print(type(element))

# Printing data types of each element in array_list
print("Data types in array_list:")
for element in array_list:
    print(type(element))

Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [3]:
# Q3: Data type change after specifying dtype=int in array_list

# Changing array_list to integer type
array_list = np.array(object = list_, dtype = int)

# Printing data types of each element in list_
print("Data types in list_:")
for element in list_:
    print(type(element))

# Printing data types of each element in array_list
print("Data types in array_list after conversion to int:")
for element in array_list:
    print(type(element))

Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data types in array_list after conversion to int:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [4]:
# Q4: Characteristics of num_array

import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object = num_list)

# Finding the shape and size of num_array
shape = num_array.shape
size = num_array.size

print(f"Shape of num_array: {shape}")
print(f"Size of num_array: {size}")

Shape of num_array: (2, 3)
Size of num_array: 6


In [5]:
# Q5: Create a 3x3 matrix containing zeros

# Creating a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))
print(zero_matrix)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Q6: Create an identity matrix of shape (5,5)

# Creating a 5x5 identity matrix
identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
